file = open('CarDescription.txt', 'w')
file.write("Car Model: Tesla Model S\n")
file.write("Color: Red\n")
file.write("Year: 2022\n")
file.write("Description: A fully electric luxury sedan with impressive performance.\n")
file.close()

file = open('CarDescription.txt', 'r')
print("Reading the entire file:")
print(file.read())
file.close()

file = open('CarDescription.txt', 'r')
print("\nReading the first 20 characters:")
print(file.read(20))
file.close()

file = open('CarDescription.txt', 'a')
file.write("Owner: John Doe\n")
file.write("Mileage: 15,000 miles\n")
file.close()

file = open('CarDescription.txt', 'r')
print("\nReading the entire file after appending:")
print(file.read())
file.close()